### ISSUE TITLE
Necrobot closed their project down

### ISSUE THREAD

**Issue by rootm0s** [GediminasMasaitis/PokeEase#16]
This means you wont be able to keep doing this project?

**Comment by QUADEMU** [comment]
https://bitbucket.org/MrTT/pokownbot
Fork for all dev and futur releases

**Comment by GediminasMasaitis** [comment]
With the news of NecroBot being taken down and permabans landing on people's heads, it will be hard to continue with development of our project. We will continue though, we just need to make a change of plan. First of all, all current development efforts will be shifted into making a bot emulator, which our project will be able to connect to, without the need of actual botting. This won't be a quick task, and will take a day or two. After that, development will continue as usual, so that when _(if)_ a fork emerges, we will have a GUI ready.

I've started working on a separate project, NecroFaker. It will emulate the behavior of NecroBot, without actually sending any requests to the Pokemon Go API. When finished, it will immensely speed up the development of NecroEase - not only will we not have to care about bans, but also we will be able to test various scenarios we would usually have trouble testing _(can't catch a Mewtwo on NecroBot!)_. Additionally, it will remove the need for internet access when developing NecroEase - which is a big deal if you have my internet provider.

I will put NecroFaker on a separate GitHub repository in a day or two, when the bot drama is over.

**Comment by QUADEMU** [comment]
Good idea at final

**Comment by geocine** [comment]
@Badboyfr do you have a fork with updated suibmodules. The submodules closed down as well

**Comment by rootm0s** [comment]
Looking forward to see what happens! :+1:
