### ISSUE TITLE
add candy count in pkmn overview and detailview

### ISSUE THREAD

**Issue by NichtDerBert** [GediminasMasaitis/PokeEase#26]
Atm the only way to see how much candy i have is the journal after catching a pkmn.
will you add it to the overview and/or detailview?

atm i add it myself, looks like this:
http://puu.sh/qEWSA/f45e10390b.jpg and http://puu.sh/qEWUI/a09a40e5e5.jpg

i cant get node.js to run here, so i cant commit, sorry, but i can post the code what i change/add iff you want to add it as i have it.

also will you add a pkmn inventory update after evolve/transfer?
atm i just add a listupdate request to the click event.

maybe i will get node.js to work so i can commit ;)

**Comment by GediminasMasaitis** [comment]
We are planning on a big pokemon info overhaul, that's why I was hesitant to put any work into it at the moment. But I added it just now - https://github.com/GediminasMasaitis/PokeEase/commit/e54f773ceee6f70a3db8e3fbf43830a8903e072e

But not in the list like in your example - it would make it a bit too cluttered for our design.

**Comment by NichtDerBert** [comment]
thanks and i dont know about the overhaul you plant.
and thanks for the work on this project
